services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finreconcile-sqlserver
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_Strong_Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local